export const GET_ITEMS = "GET_ITEMS"
export const ADD_ITEM = "ADD_ITEM"
export const DELETE_ITEM = "DELETE_ITEM"
export const EDIT_ITEM = "EDIT_ITEM"
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED"
export const GET_SINGLE_ITEM = "GET_SINGLE_ITEM"
